### ISSUE TITLE
Wrong calculation

### ISSUE THREAD

**Issue by edysegura** [univas-first-exam/andreluiz93-paycheck#1]
This application isn't doing the right calculation.

![image](https://cloud.githubusercontent.com/assets/5324414/10747792/98b649fa-7c40-11e5-914c-07279cb4ba19.png)

You can check that values at this address: http://www.calculador.com.br/calculo/salario-liquido

**Comment by andreluiz93** [comment]
The issue are fixed!
https://github.com/univas-first-exam/andreluiz93-paycheck/commit/74bfd25b617fb9e5fa2c3d1aab49afe709d8088b#diff-ce4a199498207a3e09db338a54774accR13
