### ISSUE TITLE
Layout improvement

### ISSUE THREAD

**Issue by edysegura** [univas-first-exam/andreluiz93-paycheck#2]
This application needs a layout improvement to looks like what was asked in the exam.

![image](https://cloud.githubusercontent.com/assets/5324414/10747876/6d339b74-7c41-11e5-8706-f02ab240a081.png)

![image](https://cloud.githubusercontent.com/assets/5324414/10747889/95576086-7c41-11e5-8870-5517ab4b419e.png)

**Comment by andreluiz93** [comment]
Its fixed!
![image](https://cloud.githubusercontent.com/assets/10867302/10779133/c20b4ab6-7d13-11e5-817c-82616fff8e47.png)

**Comment by edysegura** [comment]
Better!
