### ISSUE TITLE
Performance improviment

### ISSUE THREAD

**Issue by edysegura** [univas-first-exam/andreluiz93-paycheck#3]
Hi @andreluiz93!

You can improve the performance of you code using [] instead of [new Array()](https://github.com/univas-first-exam/andreluiz93-paycheck/blob/master/JS/paycheckService.js#L25)

Reading suggestion, 14. Use [] Instead of New Array() at http://code.tutsplus.com/tutorials/24-javascript-best-practices-for-beginners--net-5399

**Comment by andreluiz93** [comment]
Its Fixed!!
https://github.com/univas-first-exam/andreluiz93-paycheck/commit/ca3c853e03affd4ea0243c595f41b419ecf3f335?diff=unified#diff-c28edf05a2bd091cb9baa8e66ac9065fL25

**Comment by edysegura** [comment]
Pretty good! Keep it going!
